# Generated by Django 3.0.8 on 2020-08-07 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_image_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер картинки'),
        ),
        migrations.AlterField(
            model_name='image',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.Place', verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='place',
            name='long_description',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
    ]
